[package]
name = "hiwkhao"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "parser",
    "scanner",
    "codegen",
    "preprocessor"
]

[dependencies]
scanner = { path = "./scanner" }
parser = { path = "./parser" }
