[package]
name = "hiwkhao"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
    "parser",
    "scanner",
    "codegen",
    "preprocessor",
    "emulator"
]

[dependencies]
scanner = { path = "scanner" }
parser_lib = { path = "parser" }
codegen_lib = { path = "codegen" }
