[package]
name = "codegen_lib"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "codegen"
path = "src/main.rs"

[dependencies]
parser_lib = { path = "../parser" }
scanner = { path = "../scanner" }