[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "codegen"
path = "src/main.rs"

[dependencies]
parser = { path = "../parser" }
scanner = { path = "../scanner" }