[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.27.0"
ratatui = "0.24.0"
iced = { version = "0.10", features = ["default", "tokio"] }

[lib]
name = "emulator"
path = "src/lib.rs"

[[bin]]
name = "emulator"
path = "src/main.rs"
