name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate grammar
      run: cargo run -p preprocessor -r
    - name: Build
      run: cargo build --all -r
    - name: Run tests
      run: cargo test --all -r
    - name: Compile x86_64-pc-windows-gnu
      id: x86_64-pc-windows-compile
      uses: rust-build/rust-build.action@v1.4.5
      with:
        TOOLCHAIN_VERSION: stable
        RUSTTARGET: x86_64-pc-windows-gnu
        UPLOAD_MODE: none
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-pc-windows-gnu
        path: |
          ${{ steps.x86_64-pc-windows-compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.x86_64-pc-windows-compile.outputs.BUILT_CHECKSUM }}
    - name: Compile x86_64-unknown-linux-musl
      id: x86_64-unknown-linux-musl-compile
      uses: rust-build/rust-build.action@v1.4.5
      with:
        TOOLCHAIN_VERSION: stable
        RUSTTARGET: x86_64-unknown-linux-musl
        UPLOAD_MODE: none
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: x86_64-unknown-linux-musl
        path: |
          ${{ steps.x86_64-unknown-linux-musl-compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.x86_64-unknown-linux-musl-compile.outputs.BUILT_CHECKSUM }}
    # - name: Compile x86_64-apple-darwin
    #   id: x86_64-apple-darwin-compile
    #   uses: rust-build/rust-build.action@v1.4.5
    #   with:
    #     TOOLCHAIN_VERSION: stable
    #     RUSTTARGET: x86_64-apple-darwin
    #     UPLOAD_MODE: none
    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #     name: x86_64-apple-darwin
    #     path: |
    #       ${{ steps.x86_64-apple-darwin-compile.outputs.BUILT_ARCHIVE }}
    #       ${{ steps.x86_64-apple-darwin-compile.outputs.BUILT_CHECKSUM }}
