name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate grammar
      run: cargo run -p preprocessor -r
    - name: Build
      run: cargo build --all -r
    - name: Run tests
      run: cargo test --all -r
    - name: Compile
      id: compile
      uses: rust-build/rust-build.action@v1.4.5
      with:
        RUSTTARGET: x86_64-pc-windows-gnu
        UPLOAD_MODE: none
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Binary
        path: |
          ${{ steps.compile.outputs.BUILT_ARCHIVE }}
          ${{ steps.compile.outputs.BUILT_CHECKSUM }}
